package main

import "github.com/axogc/backend/utils"

var TestServers = []utils.Server{
	{
		ID:           1,
		Slug:         "mc-survival",
		Label:        "生存主世界",
		Path:         "/servers/minecraft/survival",
		Port:         25565,
		Description:  "经典生存模式服务器，支持建筑和冒险",
		GameID:       utils.MinecraftJava,
		BackupEnable: true,
		BackupPath:   "/backups/mc-survival",
		BackupCron:   "0 2 * * *",
		BackupLimit:  7,
		Meta: map[string]any{
			"version":     "1.20.1",
			"difficulty":  "normal",
			"max_players": 50,
			"whitelist":   false,
		},
	},
	{
		ID:           2,
		Slug:         "mc-creative",
		Label:        "创造建筑服",
		Path:         "/servers/minecraft/creative",
		Port:         25566,
		Description:  "创造模式服务器，专注于建筑创作",
		GameID:       utils.MinecraftJava,
		BackupEnable: true,
		BackupPath:   "/backups/mc-creative",
		BackupCron:   "0 3 * * *",
		BackupLimit:  5,
		Meta: map[string]any{
			"version":     "1.20.1",
			"difficulty":  "peaceful",
			"max_players": 30,
			"whitelist":   true,
		},
	},
	{
		ID:           3,
		Slug:         "mcbe-mobile",
		Label:        "手机版联机",
		Path:         "/servers/minecraft/bedrock",
		Port:         19132,
		Description:  "基岩版服务器，支持手机和主机联机",
		GameID:       utils.MinecraftBedrock,
		BackupEnable: true,
		BackupPath:   "/backups/mcbe-mobile",
		BackupCron:   "0 4 * * *",
		BackupLimit:  10,
		Meta: map[string]any{
			"version":     "1.20.30",
			"difficulty":  "normal",
			"max_players": 20,
			"pvp":         false,
		},
	},
	{
		ID:           4,
		Slug:         "terraria-expert",
		Label:        "泰拉瑞亚专家",
		Path:         "/servers/terraria/expert",
		Port:         7777,
		Description:  "专家模式泰拉瑞亚服务器，挑战更高难度",
		GameID:       utils.Terraria,
		BackupEnable: true,
		BackupPath:   "/backups/terraria-expert",
		BackupCron:   "0 1 * * *",
		BackupLimit:  14,
		Meta: map[string]any{
			"version":     "1.4.4.9",
			"difficulty":  "expert",
			"max_players": 8,
			"pvp":         true,
		},
	},
}
