package main

import "github.com/axogc/backend/utils"

var TestServers = []utils.Server{
	{
		ID:           1,
		Slug:         "main",
		Label:        "互通服务器",
		Path:         "/srv/main/",
		Port:         25565,
		Description:  "经典互通服务器，支持基岩版、Java版",
		GameID:       utils.MinecraftJava,
		BackupEnable: true,
		BackupPath:   "/srv/main/backups/",
		BackupCron:   "0 5 * * *",
		BackupLimit:  5,
		Meta:         nil,
	},
	{
		ID:           2,
		Slug:         "bedrock",
		Label:        "基岩版服务器",
		Path:         "/srv/bedrock/",
		Port:         19132,
		Description:  "基岩版服务器，安装了农夫乐事、家具等模组",
		GameID:       utils.MinecraftBedrock,
		BackupEnable: true,
		BackupPath:   "/srv/bedrock/backups/",
		BackupCron:   "0 5 * * *",
		BackupLimit:  5,
		Meta:         nil,
	},
	{
		ID:           3,
		Slug:         "fabric",
		Label:        "模组服务器",
		Path:         "/srv/fabric/",
		Port:         25566,
		Description:  "我的世界Java版模组服务器",
		GameID:       utils.MinecraftJava,
		BackupEnable: true,
		BackupPath:   "/srv/farbic/backups/",
		BackupCron:   "0 5 * * *",
		BackupLimit:  5,
		Meta:         nil,
	},
	{
		ID:           4,
		Slug:         "dont-starve",
		Label:        "饥荒联机版",
		Path:         "/srv/dont-starve/",
		Port:         10999,
		Description:  "饥荒联机版服务器，密码咨询管理员",
		GameID:       utils.DontStarve,
		BackupEnable: true,
		BackupPath:   "/srv/dont-starve/backups/",
		BackupCron:   "0 5 * * *",
		BackupLimit:  5,
	},
	{
		ID:           5,
		Slug:         "terraria",
		Label:        "泰拉瑞亚",
		Path:         "/srv/terraria/",
		Port:         7777,
		Description:  "专家模式泰拉瑞亚服务器，密码咨询管理员",
		GameID:       utils.Terraria,
		BackupEnable: true,
		BackupPath:   "/srv/terraria/backups/",
		BackupCron:   "0 5 * * *",
		BackupLimit:  5,
		Meta:         nil,
	},
}
